// <auto-generated />
using LocalBusinessAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusinessAPI.Migrations
{
    [DbContext(typeof(LocalBusinessAPIContext))]
    [Migration("20220401211702_MoreData")]
    partial class MoreData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LocalBusinessAPI.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Location = "Over there",
                            Name = "Costco",
                            Type = "Retail"
                        },
                        new
                        {
                            BusinessId = 2,
                            Location = "Over there",
                            Name = "Mcdonalds",
                            Type = "Fast food"
                        },
                        new
                        {
                            BusinessId = 3,
                            Location = "Over there",
                            Name = "Walmart",
                            Type = "Retail"
                        },
                        new
                        {
                            BusinessId = 4,
                            Location = "Over there",
                            Name = "Walgreens",
                            Type = "Pharmacy"
                        },
                        new
                        {
                            BusinessId = 5,
                            Location = "Over there",
                            Name = "Hardees",
                            Type = "Fast food"
                        },
                        new
                        {
                            BusinessId = 6,
                            Location = "Over there",
                            Name = "Armani",
                            Type = "Luxury"
                        },
                        new
                        {
                            BusinessId = 7,
                            Location = "Over there",
                            Name = "ToysRus",
                            Type = "Toys"
                        },
                        new
                        {
                            BusinessId = 8,
                            Location = "Over there",
                            Name = "Best Buy",
                            Type = "Electronics"
                        },
                        new
                        {
                            BusinessId = 9,
                            Location = "Over there",
                            Name = "Lil Caesars",
                            Type = "Pizza"
                        },
                        new
                        {
                            BusinessId = 10,
                            Location = "Over there",
                            Name = "Frank's",
                            Type = "Sandwiches"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
